// SPDX-License-Identifier: GPL-2.0-only
/*
 * Copyright (C) 2026 dere3046
 */

#include <linux/export.h>

#include "helpers.h"
#include "shim.h"

#define EXPORT_SYMBOL_RUST_GPL(sym) extern int sym; EXPORT_SYMBOL_GPL(sym)

#ifndef CONFIG_RUST
EXPORT_SYMBOL_GPL(rust_helper_BUG);
EXPORT_SYMBOL_GPL(rust_helper_ERR_PTR);
EXPORT_SYMBOL_GPL(rust_helper_IS_ERR);
EXPORT_SYMBOL_GPL(rust_helper_PTR_ERR);
EXPORT_SYMBOL_GPL(rust_helper_errname);
EXPORT_SYMBOL_GPL(rust_helper_get_current);
EXPORT_SYMBOL_GPL(rust_helper_get_task_struct);
EXPORT_SYMBOL_GPL(rust_helper_put_task_struct);
EXPORT_SYMBOL_GPL(rust_helper_task_uid);
EXPORT_SYMBOL_GPL(rust_helper_task_euid);
EXPORT_SYMBOL_GPL(rust_helper_from_kuid);
EXPORT_SYMBOL_GPL(rust_helper_uid_eq);
EXPORT_SYMBOL_GPL(rust_helper_current_euid);
EXPORT_SYMBOL_GPL(rust_helper_current_user_ns);
EXPORT_SYMBOL_GPL(rust_helper_task_tgid_nr_ns);
EXPORT_SYMBOL_GPL(rust_helper_task_rlimit);
EXPORT_SYMBOL_GPL(rust_helper_get_pid_ns);
EXPORT_SYMBOL_GPL(rust_helper_put_pid_ns);
EXPORT_SYMBOL_GPL(rust_helper_task_get_pid_ns);
EXPORT_SYMBOL_GPL(rust_helper_alloc_pages);
EXPORT_SYMBOL_GPL(rust_helper_kmap_local_page);
EXPORT_SYMBOL_GPL(rust_helper_kunmap_local);
EXPORT_SYMBOL_GPL(rust_helper_copy_from_user);
EXPORT_SYMBOL_GPL(rust_helper_copy_to_user);
EXPORT_SYMBOL_GPL(rust_helper_krealloc);
EXPORT_SYMBOL_GPL(rust_helper_kvrealloc);
EXPORT_SYMBOL_GPL(rust_helper_vrealloc);
EXPORT_SYMBOL_GPL(rust_helper_signal_pending);
EXPORT_SYMBOL_GPL(rust_helper_poll_wait);
EXPORT_SYMBOL_GPL(rust_helper_init_wait);
EXPORT_SYMBOL_GPL(rust_helper___mutex_init);
EXPORT_SYMBOL_GPL(rust_helper_mutex_lock);
EXPORT_SYMBOL_GPL(rust_helper___spin_lock_init);
EXPORT_SYMBOL_GPL(rust_helper_spin_lock);
EXPORT_SYMBOL_GPL(rust_helper_spin_unlock);
EXPORT_SYMBOL_GPL(rust_helper_spin_trylock);
EXPORT_SYMBOL_GPL(rust_helper_REFCOUNT_INIT);
EXPORT_SYMBOL_GPL(rust_helper_refcount_inc);
EXPORT_SYMBOL_GPL(rust_helper_refcount_dec_and_test);
EXPORT_SYMBOL_GPL(rust_helper_get_cred);
EXPORT_SYMBOL_GPL(rust_helper_put_cred);
EXPORT_SYMBOL_GPL(rust_helper_get_file);
EXPORT_SYMBOL_GPL(rust_helper_i_size_read);
#endif

EXPORT_SYMBOL_GPL(rs_errname);
EXPORT_SYMBOL_GPL(rs_kvrealloc);
EXPORT_SYMBOL_GPL(rs_vrealloc);
EXPORT_SYMBOL_GPL(rs_find_vm_area);
EXPORT_SYMBOL_GPL(rs_list_lru_count);
EXPORT_SYMBOL_GPL(rs_list_lru_walk);
EXPORT_SYMBOL_GPL(rs_mmput);
EXPORT_SYMBOL_GPL(rs_mmput_async);
EXPORT_SYMBOL_GPL(rs_zap_page_range_single);
EXPORT_SYMBOL_GPL(rs_vm_insert_page);
EXPORT_SYMBOL_GPL(rs_get_device);
EXPORT_SYMBOL_GPL(rs_put_device);
EXPORT_SYMBOL_GPL(rs_request_firmware);
EXPORT_SYMBOL_GPL(rs_firmware_request_nowarn);
EXPORT_SYMBOL_GPL(rs_release_firmware);
EXPORT_SYMBOL_GPL(rs_misc_register);
EXPORT_SYMBOL_GPL(rs_misc_deregister);
EXPORT_SYMBOL_GPL(rs__copy_from_iter);
EXPORT_SYMBOL_GPL(rs__copy_to_iter);
EXPORT_SYMBOL_GPL(rs_generic_file_open);
EXPORT_SYMBOL_GPL(rs___blk_mq_alloc_disk);
EXPORT_SYMBOL_GPL(rs_set_capacity);
EXPORT_SYMBOL_GPL(rs_device_add_disk);
EXPORT_SYMBOL_GPL(rs_del_gendisk);
EXPORT_SYMBOL_GPL(rs_blk_mq_start_request);
EXPORT_SYMBOL_GPL(rs_blk_mq_end_request);
EXPORT_SYMBOL_GPL(rs_blk_mq_alloc_tag_set);
EXPORT_SYMBOL_GPL(rs_blk_mq_free_tag_set);
EXPORT_SYMBOL_GPL(rs_errno_to_blk_status);
EXPORT_SYMBOL_GPL(rs_queue_work_on);
EXPORT_SYMBOL_GPL(rs_rb_first);
EXPORT_SYMBOL_GPL(rs_rb_last);
EXPORT_SYMBOL_GPL(rs_rb_first_postorder);
EXPORT_SYMBOL_GPL(rs_rb_next_postorder);
EXPORT_SYMBOL_GPL(rs_rb_prev);
EXPORT_SYMBOL_GPL(rs_rb_next);
EXPORT_SYMBOL_GPL(rs_rb_erase);
EXPORT_SYMBOL_GPL(rs_rb_insert_color);
EXPORT_SYMBOL_GPL(rs_rb_replace_node);
EXPORT_SYMBOL_GPL(rs_rb_left);
EXPORT_SYMBOL_GPL(rs_rb_right);
EXPORT_SYMBOL_GPL(rs_rb_left_ptr);
EXPORT_SYMBOL_GPL(rs_rb_right_ptr);
EXPORT_SYMBOL_GPL(rs_rb_root_node);
EXPORT_SYMBOL_GPL(rs_rb_root_node_ptr);
EXPORT_SYMBOL_GPL(rs_system_wq);
EXPORT_SYMBOL_GPL(rs_system_highpri_wq);
EXPORT_SYMBOL_GPL(rs_system_long_wq);
EXPORT_SYMBOL_GPL(rs_system_unbound_wq);
EXPORT_SYMBOL_GPL(rs_system_freezable_wq);
EXPORT_SYMBOL_GPL(rs_system_power_efficient_wq);
EXPORT_SYMBOL_GPL(rs_system_freezable_power_efficient_wq);
EXPORT_SYMBOL_GPL(rs_vma_mm);
EXPORT_SYMBOL_GPL(rs_vma_flags);
EXPORT_SYMBOL_GPL(rs_vma_start);
EXPORT_SYMBOL_GPL(rs_vma_end);
EXPORT_SYMBOL_GPL(rs_vma_set_flags);
EXPORT_SYMBOL_GPL(rs_file_private_data);
EXPORT_SYMBOL_GPL(rs_file_set_private_data);
EXPORT_SYMBOL_GPL(rs_cred_euid);
EXPORT_SYMBOL_GPL(rs__printk);
EXPORT_SYMBOL_GPL(rs_seq_printf);
EXPORT_SYMBOL_GPL(rs___free_pages);
EXPORT_SYMBOL_GPL(rs__copy_from_user);
EXPORT_SYMBOL_GPL(rs__copy_to_user);
EXPORT_SYMBOL_GPL(rs_strncpy_from_user);
EXPORT_SYMBOL_GPL(rs_memchr);
EXPORT_SYMBOL_GPL(rs_strlen);
EXPORT_SYMBOL_GPL(rs___init_waitqueue_head);
EXPORT_SYMBOL_GPL(rs_prepare_to_wait_exclusive);
EXPORT_SYMBOL_GPL(rs_schedule_timeout);
EXPORT_SYMBOL_GPL(rs___wake_up);
EXPORT_SYMBOL_GPL(rs___wake_up_sync);
EXPORT_SYMBOL_GPL(rs_finish_wait);
EXPORT_SYMBOL_GPL(rs_synchronize_rcu);
EXPORT_SYMBOL_GPL(rs___wake_up_pollfree);
EXPORT_SYMBOL_GPL(rs_set_user_nice);
EXPORT_SYMBOL_GPL(rs_sched_setscheduler_nocheck);
EXPORT_SYMBOL_GPL(rs_has_capability_noaudit);
EXPORT_SYMBOL_GPL(rs_task_active_pid_ns);
EXPORT_SYMBOL_GPL(rs_wake_up_process);
EXPORT_SYMBOL_GPL(rs_mutex_unlock);
EXPORT_SYMBOL_GPL(rs_mutex_trylock);
EXPORT_SYMBOL_GPL(rs_task_pid);
EXPORT_SYMBOL_GPL(rs_task_tgid);
EXPORT_SYMBOL_GPL(rs_task_group_leader);
EXPORT_SYMBOL_GPL(rs_task_mm);
EXPORT_SYMBOL_GPL(rs_task_policy);
EXPORT_SYMBOL_GPL(rs_task_normal_prio);
EXPORT_SYMBOL_GPL(rs_task_cred);
EXPORT_SYMBOL_GPL(rs_page_nid);

#include "exports_rust_generated.h"
